// regen-thumbs: standalone tool to regenerate all thumb_<hash>.png in a
// given directory using the EXACT same logic as
// backend/api/internal/handler/thumbnail.go:generateThumbnail.
//
// This is NOT a production code change. It is a one-shot migration to
// refresh stale thumbnails that were generated by an earlier version
// of the thumbnail code and lost their alpha channel.
//
// The algorithm itself lives in internal/thumbnail/thumbnail.go and
// is shared with the live upload handler, so this tool and the
// handler cannot drift apart — byte-identical output is guaranteed
// by construction.
//
// Usage: regen-thumbs <uploads-dir>
//   - Reads every *.png/*.jpg/*.jpeg/*.webp in the directory (excluding
//     names starting with "thumb_").
//   - Writes thumb_<name>.png next to it, 400x300 max bounds, Catmull-Rom
//     scaling with alpha preserved (draw.Over on a zeroed RGBA canvas).
//
// Safety:
//   - Never deletes or overwrites source files.
//   - Idempotent: re-running produces the same output.
//   - Skips already-existing thumb_<name>.png UNLESS --force is given.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"mioru/internal/thumbnail"
)

const (
	maxWidth  = 400
	maxHeight = 300
)

// regenSourceExts lists which upload extensions the regen-thumbs tool
// should walk. Mirrors allowedImageExts in handler/image.go so the tool
// doesn't silently skip JPEG/WebP files after that allowlist is expanded
// (PR #57 L2 finding). Kept here as a local const rather than imported
// from the handler package — regen-thumbs is intentionally a standalone
// cmd with a narrow surface and should not pull in the whole handler
// stack just for the extension list.
var regenSourceExts = map[string]bool{
	".png":  true,
	".jpg":  true,
	".jpeg": true,
	".webp": true,
}

func main() {
	dir := flag.String("dir", "", "uploads directory containing full-size *.png/*.jpg/*.jpeg/*.webp")
	force := flag.Bool("force", false, "regenerate even if thumb_<name>.png already exists")
	dryRun := flag.Bool("dry-run", false, "list what would be processed, do not write")
	flag.Parse()

	if *dir == "" {
		fmt.Fprintln(os.Stderr, "usage: regen-thumbs --dir <uploads-dir> [--force] [--dry-run]")
		os.Exit(2)
	}

	// filepath.Glob does not support {a,b,c} brace expansion, so list the
	// directory and filter by the regen source extensions. ReadDir returns
	// names sorted (matches the previous filepath.Glob ordering), so the
	// output here is deterministic.
	entries, err := os.ReadDir(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", *dir, err)
		os.Exit(1)
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, "thumb_") {
			continue // never process thumb_*.png as source
		}
		if !regenSourceExts[strings.ToLower(filepath.Ext(name))] {
			continue
		}
		files = append(files, filepath.Join(*dir, name))
	}

	var processed, skipped, failed int
	for _, src := range files {
		name := filepath.Base(src)
		if strings.HasPrefix(name, "thumb_") {
			continue // never process thumb_*.png as source
		}
		thumbPath := filepath.Join(*dir, "thumb_"+name)

		// Skip if thumb already exists and --force not set
		if !*force {
			if _, err := os.Stat(thumbPath); err == nil {
				skipped++
				continue
			}
		}

		if *dryRun {
			fmt.Printf("would regen: %s -> %s\n", src, thumbPath)
			processed++
			continue
		}

		// Shared algorithm with the live handler — see
		// internal/thumbnail/thumbnail.go for the implementation.
		if err := thumbnail.Generate(src, thumbPath, maxWidth, maxHeight); err != nil {
			fmt.Fprintf(os.Stderr, "FAIL  %s: %v\n", name, err)
			failed++
			continue
		}
		processed++
	}

	fmt.Printf("\nDone: %d processed, %d skipped (already exist), %d failed\n",
		processed, skipped, failed)
	if failed > 0 {
		os.Exit(1)
	}
}
