// regen-thumbs: standalone tool to regenerate all thumb_<hash>.png in a
// given directory using the EXACT same logic as
// backend/api/internal/handler/thumbnail.go:generateThumbnail.
//
// This is NOT a production code change. It is a one-shot migration to
// refresh stale thumbnails that were generated by an earlier version
// of the thumbnail code and lost their alpha channel.
//
// Usage: regen-thumbs <uploads-dir>
//   - Reads every *.png in the directory (excluding names starting with
//     "thumb_").
//   - Writes thumb_<name>.png next to it, 400x300 max bounds, Catmull-Rom
//     scaling with alpha preserved (draw.Over on a zeroed RGBA canvas).
//
// Safety:
//   - Never deletes or overwrites source files.
//   - Idempotent: re-running produces the same output.
//   - Skips already-existing thumb_<name>.png UNLESS --force is given.
package main

import (
	"flag"
	"fmt"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/image/draw"
)

const (
	maxWidth  = 400
	maxHeight = 300
)

func main() {
	dir := flag.String("dir", "", "uploads directory containing full-size *.png")
	force := flag.Bool("force", false, "regenerate even if thumb_<name>.png already exists")
	dryRun := flag.Bool("dry-run", false, "list what would be processed, do not write")
	flag.Parse()

	if *dir == "" {
		fmt.Fprintln(os.Stderr, "usage: regen-thumbs --dir <uploads-dir> [--force] [--dry-run]")
		os.Exit(2)
	}

	files, err := filepath.Glob(filepath.Join(*dir, "*.png"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "glob: %v\n", err)
		os.Exit(1)
	}

	var processed, skipped, failed int
	for _, src := range files {
		name := filepath.Base(src)
		if strings.HasPrefix(name, "thumb_") {
			continue // never process thumb_*.png as source
		}
		thumb := filepath.Join(*dir, "thumb_"+name)

		// Skip if thumb already exists and --force not set
		if !*force {
			if _, err := os.Stat(thumb); err == nil {
				skipped++
				continue
			}
		}

		if *dryRun {
			fmt.Printf("would regen: %s -> %s\n", src, thumb)
			processed++
			continue
		}

		if err := regenThumbnail(src, thumb); err != nil {
			fmt.Fprintf(os.Stderr, "FAIL  %s: %v\n", name, err)
			failed++
			continue
		}
		processed++
	}

	fmt.Printf("\nDone: %d processed, %d skipped (already exist), %d failed\n",
		processed, skipped, failed)
	if failed > 0 {
		os.Exit(1)
	}
}

// regenThumbnail is a byte-for-byte port of
// handler/generateThumbnail. Any drift here is a bug — the whole point
// of the migration is that the OUTPUT matches what future uploads will
// produce.
func regenThumbnail(srcPath, dstPath string) error {
	src, err := os.Open(srcPath)
	if err != nil {
		return err
	}
	defer src.Close()

	// Decompression-bomb guard (50 megapixels, same as handler).
	const maxPixels = 50_000_000
	cfg, err := png.DecodeConfig(src)
	if err != nil {
		return fmt.Errorf("decode config: %w", err)
	}
	if cfg.Width*cfg.Height > maxPixels {
		return fmt.Errorf("image too large: %d×%d (max %d pixels)", cfg.Width, cfg.Height, maxPixels)
	}
	if _, err := src.Seek(0, 0); err != nil {
		return fmt.Errorf("seek: %w", err)
	}

	img, err := png.Decode(src)
	if err != nil {
		return fmt.Errorf("decode: %w", err)
	}

	bounds := img.Bounds()
	srcW, srcH := bounds.Dx(), bounds.Dy()
	scale := float64(maxWidth) / float64(srcW)
	if hScale := float64(maxHeight) / float64(srcH); hScale < scale {
		scale = hScale
	}
	dstW := int(float64(srcW) * scale)
	dstH := int(float64(srcH) * scale)

	dst := image.NewRGBA(image.Rect(0, 0, dstW, dstH))
	draw.CatmullRom.Scale(dst, dst.Bounds(), img, bounds, draw.Over, nil)

	out, err := os.Create(dstPath)
	if err != nil {
		return err
	}
	defer out.Close()
	if err := png.Encode(out, dst); err != nil {
		return fmt.Errorf("encode: %w", err)
	}
	return out.Close()
}
