-- 005_super_admin: super_admin role assignment is handled in
-- the Go bootstrap path (seedAdmin/BOOTSTRAP_ADMIN_USERNAME),
-- not via a hardcoded SQL username. This migration remains as a
-- version placeholder for schema continuity; fresh installs get
-- the role from seedAdmin at first startup.
